#!/bin/bash

# Define colors
GREEN='\033[0;32m'
YELLOW='\033[0;33m'
NC='\033[0m' # No Color

# Define arrays for source files and their corresponding target paths
declare -A files_to_link=(
    ["tmux.conf"]="$HOME/.tmux.conf"
    ["init.lua"]="$HOME/.config/nvim/init.lua"
)

# Set the alignment width (200 chars)
ALIGN_WIDTH=80

# Function to create symbolic links
create_symlink() {
    local src=$1
    local dst=$2
    local dir

    # Extract the directory from the target path
    dir=$(dirname $dst)
    
    # Create the directory if it doesn't exist
    mkdir -p $dir
    
    if [ -f $dst ]; then
        printf "${YELLOW}%-${ALIGN_WIDTH}s %s${NC}\n" "Skipping '$dst'" "already exists"
    else
        ln -s ${PWD}/$src $dst
        printf "${GREEN}%-${ALIGN_WIDTH}s %s${NC}\n" "Linked '$dst'" "Linked"
    fi
}

# Iterate over the array and create symbolic links
for src in "${!files_to_link[@]}"; do
    create_symlink $src ${files_to_link[$src]}
done

